on:
  push:
    branches: main

name: gen_io_page

jobs:
  gen_page:
    runs-on: macOS-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          brew install hugo rsync

      - name: Build Site
        run: |
          make

      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "noreply@github.com"

      - name: Setup deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone github.io page
        run: |
          git clone git@github.com:rundel/rundel.github.io.git

      - name: Sync changes
        run: |
          rsync -a --delete --exclude=".*" public/ rundel.github.io/

      - name: Commit and push changes
        run: |
          cd rundel.github.io/
          git add .
          if git diff --cached --quiet; then
            echo "No changes to publish"
          else
            git commit -m "Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
            git push
          fi
